### ISSUE TITLE
not run

### ISSUE THREAD

**Issue by amirmansoori** [Tyriar/vscode-theme-generator-quick-start#3] opened 2021-09-11 18:29 UTC
node_modules/@types/node/index.d.ts:20:1 - error TS1084: Invalid 'reference' 
directive syntax.

20 /// <reference lib="es2016" />
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by Tyriar** [comment] 2021-09-14 15:27
duplicate of https://github.com/Tyriar/vscode-theme-generator-quick-start/issues/2

**Closed as completed by Tyriar** 2021-09-14 15:27 UTC
Labels: duplicate
